feat: structure docs in content directory
shabados/docs pull request #11
Opened 2020-11-08 02:33 UTC by saihaj

### Summary of PR
* [X] Remove old boilerplates docs and blog pages
* [X] Add dummy pages for ShabadOS products
* [X] Add products to main navigation bar
* [X] Add product tiles to homepage
* [ ] Style homepage product tiles (need help @bhajneet)

They way I have structured docs is that all the product docs go in `content/`. Make a folder for product. Markdown files need to get processed so we can generate pages, it also needs to know route it should serve docs on. So we fill in `src/pages.config.js` and add route, path, sidebar and other information. This way allows us to customize product docs independently. We can have different layouts and many other features (I can't think of any for now except layout).

For now `docs` directory is not used for anything and I tried researching to remove it but no success yet. I need it because of the base theme to apply.  So I plan to put all the docs for this site and maybe move over our wiki from `.github` repo. Something we can discuss in future what to do. But for now we should ignore this and I will handle it in future PR.

### Time spent on PR
7 hours - Spent too much time researching and finding an elegant way to have multiple docs and make it easy to just add new products in future.

### Reviewers
@Harjot1Singh @bhajneet

2020-11-12 03:08 UTC, Harjot1Singh requested changes
Aside from the inconsequential stylstic issues highlighted, looks good.

I personally like keeping the content under `content`. I reckon it'd be good for each content folder to have a `sidebar.json` similar to https://github.com/facebook/react-native-website/blob/master/website/sidebars.json

2020-11-12 03:08 UTC, Harjot1Singh commented on docusaurus.config.js
> +    ...pages,
Why spread them?

2020-11-12 03:08 UTC, Harjot1Singh commented on src/pages/index.js
> +              { products.map( ( { title, description } ) => (
```suggestion
              {products.map( ( { title, description } ) => (
```

2020-11-12 03:08 UTC, Harjot1Singh commented on docusaurus.config.js
> +        { to: '/',
lol wut formatting is dis

2020-11-18 17:55 UTC, saihaj commented
> I personally like keeping the content under content. I reckon it'd be good for each content folder to have a sidebar.json similar to https://github.com/facebook/react-native-website/blob/master/website/sidebars.json

Yes idea is that inside `src/sidebars` we will have sidebars for each directory that is in `content`. This is something my next PR will bring.

2020-11-18 17:58 UTC, saihaj commented on docusaurus.config.js
> +    ...pages,
see `src/pages.config.js` the config was getting very big and there was repetition. So I decided to move `pages` plugins to that. So in future one just needs to add this to the `pages` array in `src/pages.config.js`
```
  [
    '@docusaurus/plugin-content-docs',
    {
      ...sharedValues,
      id: 'someCoolProject',
      path: 'content/someCoolProject',
      routeBasePath: 'someCoolProject',
    },
  ],
```

2020-11-20 00:27 UTC, Harjot1Singh commented on docusaurus.config.js
> +    ...pages,
Yeah, that makes sense, but you're doing `plugins: [ ...pages ]` which is the exact same as `plugins: pages`, unless I'm missing something.

2020-11-20 00:30 UTC, saihaj commented on docusaurus.config.js
> +    ...pages,
We can add more plugins so that is why I did spread. But right now there is nothing I can change it

2020-11-20 00:39 UTC, Harjot1Singh commented on docusaurus.config.js
> +    ...pages,
Oh, I see. No problem.

2020-11-20 00:39 UTC, Harjot1Singh approved these changes

2020-11-20 00:39 UTC, merged